//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.UnitTests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareDirectorCore_CDEntities : DbContext
    {
        public CareDirectorCore_CDEntities()
            : base("name=CareDirectorCore_CDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Professional> Professionals { get; set; }
        public virtual DbSet<Provider> Providers { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
    }
}
