//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professional()
        {
            this.Providers = new HashSet<Provider>();
        }
    
        public System.Guid ProfessionalId { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<System.Guid> ProfessionTypeId { get; set; }
        public int ProfessionalNumber { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string ProfessionalCode { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullAddress { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<System.Guid> AddressPropertyTypeId { get; set; }
        public string AddressLine3 { get; set; }
        public string UPRN { get; set; }
        public string AddressLine4 { get; set; }
        public Nullable<System.Guid> AddressBoroughId { get; set; }
        public string AddressLine5 { get; set; }
        public Nullable<System.Guid> AddressWardId { get; set; }
        public string Postcode { get; set; }
        public string BusinessPhone { get; set; }
        public string Email { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<System.Guid> ContactMethodId { get; set; }
        public Nullable<bool> AllowEmail { get; set; }
        public Nullable<bool> AllowPhone { get; set; }
        public Nullable<bool> AllowMail { get; set; }
        public Nullable<int> GenderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
    }
}
