//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provider()
        {
            this.Provider1 = new HashSet<Provider>();
        }
    
        public System.Guid ProviderId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> OwnerId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string Name { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<System.Guid> OwningBusinessUnitId { get; set; }
        public string LegacyId { get; set; }
        public int ProviderNumber { get; set; }
        public string MainPhone { get; set; }
        public string OtherPhone { get; set; }
        public string AccountNumber { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string CQCLocationId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PropertyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string AddressLine4 { get; set; }
        public string AddressLine5 { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string AddressPhone { get; set; }
        public string ContactHours { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ProviderTypeId { get; set; }
        public Nullable<System.Guid> AddressPropertyTypeId { get; set; }
        public Nullable<System.Guid> ParentProviderId { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string FullAddress { get; set; }
        public Nullable<System.Guid> ContractLeadId { get; set; }
        public Nullable<System.Guid> QALeadId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<System.Guid> PrimaryContactId { get; set; }
    
        public virtual Professional Professional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Provider1 { get; set; }
        public virtual Provider Provider2 { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual SystemUser SystemUser1 { get; set; }
        public virtual SystemUser SystemUser2 { get; set; }
        public virtual SystemUser SystemUser3 { get; set; }
    }
}
