//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.UnitTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SystemUser()
        {
            this.Professionals = new HashSet<Professional>();
            this.Professionals1 = new HashSet<Professional>();
            this.Providers = new HashSet<Provider>();
            this.Providers1 = new HashSet<Provider>();
            this.Providers2 = new HashSet<Provider>();
            this.Providers3 = new HashSet<Provider>();
        }
    
        public System.Guid SystemUserId { get; set; }
        public string UserName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> LanguageId { get; set; }
        public string WorkEmail { get; set; }
        public string JobTitle { get; set; }
        public string WorkPhoneLandline { get; set; }
        public string WorkPhoneMobile { get; set; }
        public Nullable<System.Guid> ProfilePhotoId { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string Password { get; set; }
        public Nullable<bool> CanWorkOffline { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public Nullable<System.DateTime> LastFailedPasswordAttemptDate { get; set; }
        public Nullable<System.DateTime> AccountLockedOutDate { get; set; }
        public Nullable<bool> IsAccountLocked { get; set; }
        public string SecureEmailAddress { get; set; }
        public Nullable<System.Guid> AuthenticationProviderId { get; set; }
        public Nullable<bool> IsServiceAccount { get; set; }
        public Nullable<bool> IsManager { get; set; }
        public Nullable<System.Guid> OwningBusinessUnitId { get; set; }
        public Nullable<System.Guid> DefaultTeamId { get; set; }
        public string TimeZoneId { get; set; }
        public Nullable<bool> DisableFormAutoSave { get; set; }
        public string LegacyId { get; set; }
        public bool Inactive { get; set; }
        public Nullable<int> RecordsPerPageId { get; set; }
        public string ProfessionalRegistrationNumber { get; set; }
        public Nullable<bool> CanCompleteDNAR { get; set; }
        public Nullable<bool> CanAuthoriseDNAR { get; set; }
        public Nullable<bool> IsLegitimateRelationshipEnabled { get; set; }
        public Nullable<bool> CanAuthoriseForm { get; set; }
        public Nullable<bool> CanAuthoriseOnBehalfOfOthers { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professional> Professionals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professional> Professionals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provider> Providers3 { get; set; }
    }
}
