//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audit()
        {
            this.AuditChangeSets = new HashSet<AuditChangeSet>();
        }
    
        public System.Guid AuditId { get; set; }
        public string TableName { get; set; }
        public int Operation { get; set; }
        public System.Guid RecordId { get; set; }
        public string RecordTitle { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> ErrorManagementReasonId { get; set; }
        public Nullable<System.Guid> ApplicationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditChangeSet> AuditChangeSets { get; set; }
    }
}
