//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditChangeSet_2020
    {
        public System.Guid AuditChangeSetId { get; set; }
        public System.Guid AuditId { get; set; }
        public string FieldName { get; set; }
        public string NewValue { get; set; }
        public string PreviousValue { get; set; }
        public Nullable<bool> PreviousBooleanValue { get; set; }
        public Nullable<bool> NewBooleanValue { get; set; }
        public Nullable<System.DateTime> PreviousDateValue { get; set; }
        public Nullable<System.DateTime> NewDateValue { get; set; }
        public Nullable<decimal> PreviousDecimalValue { get; set; }
        public Nullable<decimal> NewDecimalValue { get; set; }
        public Nullable<int> PreviousIntValue { get; set; }
        public Nullable<int> NewIntValue { get; set; }
        public Nullable<System.Guid> PreviousGuidValue { get; set; }
        public Nullable<System.Guid> NewGuidValue { get; set; }
        public Nullable<System.DateTime> PreviousDateTimeValue { get; set; }
        public Nullable<System.DateTime> NewDateTimeValue { get; set; }
        public Nullable<System.TimeSpan> PreviousTimeValue { get; set; }
        public Nullable<System.TimeSpan> NewTimeValue { get; set; }
        public int FieldType { get; set; }
        public string PreviousChecklistValue { get; set; }
        public string NewChecklistValue { get; set; }
    
        public virtual Audit_2020 Audit_2020 { get; set; }
    }
}
