//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Case()
        {
            this.Appointments = new HashSet<Appointment>();
            this.CaseActions = new HashSet<CaseAction>();
            this.CaseAttachments = new HashSet<CaseAttachment>();
            this.CaseForms = new HashSet<CaseForm>();
            this.CaseFormOutcomes = new HashSet<CaseFormOutcome>();
            this.Emails = new HashSet<Email>();
            this.Letters = new HashSet<Letter>();
            this.PhoneCalls = new HashSet<PhoneCall>();
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid CaseId { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<System.DateTime> ContactReceivedDateTime { get; set; }
        public Nullable<System.Guid> ContactReceivedById { get; set; }
        public Nullable<System.DateTime> RequestReceivedDateTime { get; set; }
        public string PresentingNeedDetails { get; set; }
        public string AdditionalInformation { get; set; }
        public string ContactMadeByName { get; set; }
        public Nullable<System.Guid> CommunityAndClinicTeamId { get; set; }
        public Nullable<System.DateTime> CaseAcceptedDateTime { get; set; }
        public string InformationFormReferrer { get; set; }
        public string MoreInformationResponse { get; set; }
        public Nullable<System.DateTime> MoreInformationResponseDateTime { get; set; }
        public Nullable<int> CNACount { get; set; }
        public Nullable<int> DNACount { get; set; }
        public Nullable<bool> DischargePerson { get; set; }
        public Nullable<System.Guid> DischargingProfessionalId { get; set; }
        public string AdditionalDischargeInformation { get; set; }
        public Nullable<System.DateTime> DischargeDateTime { get; set; }
        public Nullable<System.Guid> CommunityAndClinicTeamTransferredToId { get; set; }
        public Nullable<System.Guid> TeamTransferredToId { get; set; }
        public Nullable<System.DateTime> CaseTransferredDateTime { get; set; }
        public Nullable<System.Guid> ResponsibleUserId { get; set; }
        public Nullable<System.Guid> SecondaryCaseReasonId { get; set; }
        public Nullable<System.Guid> CasePriorityId { get; set; }
        public Nullable<System.Guid> CaseRejectedReasonId { get; set; }
        public Nullable<System.Guid> CaseStatusId { get; set; }
        public Nullable<System.Guid> CaseClosureReasonId { get; set; }
        public Nullable<System.Guid> InitialContactId { get; set; }
        public Nullable<System.Guid> OtherRelatedContactId { get; set; }
        public Nullable<System.Guid> ContactReasonId { get; set; }
        public Nullable<System.Guid> PresentingPriorityId { get; set; }
        public Nullable<System.Guid> CaseTransferredTeamFromId { get; set; }
        public Nullable<System.Guid> AdministrativeCategoryId { get; set; }
        public Nullable<System.Guid> ServiceTypeRequestedId { get; set; }
        public Nullable<int> PersonAwareOfContactId { get; set; }
        public Nullable<int> PersonSupportContactId { get; set; }
        public Nullable<int> CarerAwareOfContactId { get; set; }
        public Nullable<int> CarerSupportContactId { get; set; }
        public Nullable<int> NextOfKinAwareOfContactId { get; set; }
        public Nullable<int> CaseAcceptedId { get; set; }
        public Nullable<System.Guid> ProfessionalTypeId { get; set; }
        public Nullable<System.Guid> ContactMadeById { get; set; }
        public string ContactMadeByIdTableName { get; set; }
        public string ContactMadeByIdName { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.Guid> DataFormId { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<System.Guid> ContactSourceId { get; set; }
        public Nullable<int> PersonAge { get; set; }
        public Nullable<System.Guid> ChildInNeedCodeId { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.Guid> ClosureAcceptedById { get; set; }
        public Nullable<System.DateTime> ArchiveDate { get; set; }
        public Nullable<bool> PoliceNotified { get; set; }
        public Nullable<System.DateTime> PoliceNotifiedDate { get; set; }
        public string PoliceNotes { get; set; }
        public Nullable<bool> ReReferral { get; set; }
        public string ReferringAgencyCaseId { get; set; }
        public Nullable<bool> ResponseMadeToContact { get; set; }
        public string NonMigratedWorkerName { get; set; }
        public Nullable<System.DateTime> ContactWithTrainedStaffDate { get; set; }
        public Nullable<int> CaseOriginId { get; set; }
        public Nullable<System.Guid> InpatientWardId { get; set; }
        public Nullable<System.Guid> InpatientBedId { get; set; }
        public Nullable<System.Guid> InpatientAdmissionSourceId { get; set; }
        public Nullable<System.Guid> InpatientPatientClassificationId { get; set; }
        public Nullable<System.Guid> InpatientIntendedManagementId { get; set; }
        public Nullable<int> WishNokCarerNotifiedAdmissionId { get; set; }
        public Nullable<System.Guid> WhoWasNotifiedId { get; set; }
        public Nullable<System.Guid> InpatientAdmissionMethodId { get; set; }
        public Nullable<System.Guid> CurrentConsultantId { get; set; }
        public Nullable<int> DolsConcernId { get; set; }
        public Nullable<System.Guid> NamedProfessionalId { get; set; }
        public Nullable<System.DateTime> AdmissionDateTime { get; set; }
        public Nullable<System.DateTime> DecisionToAdmitAgreedDateTime { get; set; }
        public Nullable<System.DateTime> IntendedAdmissionDate { get; set; }
        public Nullable<System.Guid> InpatientChangeIntendedAdmissionReasonId { get; set; }
        public Nullable<System.DateTime> DateIntendedAdmissionChanged { get; set; }
        public Nullable<System.DateTime> EstimatedDischargeDate { get; set; }
        public Nullable<System.DateTime> FitForDischageDate { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.Guid> InpatientBayId { get; set; }
        public Nullable<System.Guid> InpatientResponsibleWardId { get; set; }
        public Nullable<System.DateTime> ActualDischargeDateTime { get; set; }
        public string DischargeInformation { get; set; }
        public Nullable<bool> Section117AftercareEntitlement { get; set; }
        public Nullable<int> DischargedToHomeAddressId { get; set; }
        public string PropertyName { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<System.Guid> AddressPropertyTypeId { get; set; }
        public string AddressLine3 { get; set; }
        public string UPRN { get; set; }
        public string AddressLine4 { get; set; }
        public Nullable<System.Guid> AddressBoroughId { get; set; }
        public string AddressLine5 { get; set; }
        public Nullable<System.Guid> AddressWardId { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> WishesContactFromImhaId { get; set; }
        public Nullable<int> DaysAsInpatient { get; set; }
        public Nullable<int> InpatientCaseStatusId { get; set; }
        public Nullable<bool> IsPersonOnLeave { get; set; }
        public Nullable<bool> IsSwappingInpatient { get; set; }
        public Nullable<int> PathwayKeySourceId { get; set; }
        public Nullable<System.Guid> HealthPathwayKeyId { get; set; }
        public Nullable<System.Guid> InpatientTransferOfCareReasonId { get; set; }
        public Nullable<System.DateTime> ActualTransferDateTime { get; set; }
        public Nullable<System.Guid> InpatientDischargeDestinationId { get; set; }
        public Nullable<System.DateTime> PlannedDischargeDate { get; set; }
        public Nullable<bool> CarerNokNotified { get; set; }
        public Nullable<System.Guid> MHASectionOnAdmissionId { get; set; }
        public Nullable<System.Guid> CommunityHealthCaseTransferReasonId { get; set; }
        public Nullable<System.Guid> ClonedFromCase { get; set; }
        public Nullable<System.Guid> actualdischargedestinationid { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public Nullable<System.Guid> CaseReopenReasonId { get; set; }
        public Nullable<System.Guid> FollowUpTeamId { get; set; }
        public string followupteamidtablename { get; set; }
        public string followupteamidname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseAction> CaseActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseAttachment> CaseAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseForm> CaseForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFormOutcome> CaseFormOutcomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letter> Letters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneCall> PhoneCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
