//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseAttachment
    {
        public System.Guid CaseAttachmentId { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> DocumentTypeId { get; set; }
        public Nullable<System.Guid> DocumentSubTypeId { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
        public System.Guid CaseId { get; set; }
        public System.Guid PersonId { get; set; }
    
        public virtual AttachDocumentType AttachDocumentType { get; set; }
        public virtual Case Case { get; set; }
        public virtual Person Person { get; set; }
    }
}
