//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaseForm()
        {
            this.CaseFormOutcomes = new HashSet<CaseFormOutcome>();
        }
    
        public System.Guid CaseFormId { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public System.Guid DocumentId { get; set; }
        public Nullable<int> AssessmentStatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.Guid> CompletedById { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.Guid> SignedOffById { get; set; }
        public Nullable<System.DateTime> SignOffDate { get; set; }
        public Nullable<System.Guid> DocumentModifiedById { get; set; }
        public Nullable<System.DateTime> DocumentModifiedOn { get; set; }
        public Nullable<bool> SDEExecuted { get; set; }
        public Nullable<bool> AnswersInitialized { get; set; }
        public Nullable<System.Guid> FormCancellationReasonId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid CaseId { get; set; }
        public Nullable<System.Guid> ResponsibleUserId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<bool> JointCarerAssessment { get; set; }
        public Nullable<bool> SeparateAssessment { get; set; }
        public Nullable<bool> CarerDeclinedJointAssessment { get; set; }
        public Nullable<bool> NewPerson { get; set; }
        public Nullable<System.Guid> JointCarerId { get; set; }
        public Nullable<System.DateTime> TargetStartDate { get; set; }
        public Nullable<System.DateTime> TerminatedDate { get; set; }
        public Nullable<System.DateTime> TriggerDate { get; set; }
        public Nullable<System.Guid> FormDelayReasonId { get; set; }
        public Nullable<System.Guid> ClonedFromId { get; set; }
    
        public virtual Case Case { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFormOutcome> CaseFormOutcomes { get; set; }
        public virtual Document Document { get; set; }
        public virtual Person Person { get; set; }
        public virtual Person Person1 { get; set; }
    }
}
