//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentQuestionIdentifier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentQuestionIdentifier()
        {
            this.DocumentAnswers = new HashSet<DocumentAnswer>();
        }
    
        public System.Guid DocumentQuestionIdentifierId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> RowId { get; set; }
        public Nullable<System.Guid> DocumentSectionQuestionId { get; set; }
        public Nullable<System.Guid> QuestionCatalogueId { get; set; }
        public Nullable<System.Guid> PrimaryQuestionId { get; set; }
        public Nullable<System.Guid> SecondaryQuestionId { get; set; }
        public System.Guid DocumentId { get; set; }
        public System.Guid DocumentSectionId { get; set; }
        public Nullable<System.Guid> QuestionViewId { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> ManagerOverrideAllowed { get; set; }
        public Nullable<bool> MandatoryOnCompletion { get; set; }
        public Nullable<System.Guid> TableQuestionCellId { get; set; }
        public Nullable<bool> ShowSDELink { get; set; }
        public Nullable<bool> SDELinkSectionMode { get; set; }
        public Nullable<System.Guid> LinkedSubQuestionId { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public Nullable<bool> HideQuestionText { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public Nullable<int> ParentQuestionTypeId { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<bool> ApplicableToSnapshot { get; set; }
        public string LegacyId { get; set; }
        public Nullable<bool> IsReportingColumnSearchable { get; set; }
        public string ReportingColumnAlias { get; set; }
    
        public virtual Document Document { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentAnswer> DocumentAnswers { get; set; }
    }
}
