//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.CaseForms = new HashSet<CaseForm>();
            this.DocumentQuestionIdentifiers = new HashSet<DocumentQuestionIdentifier>();
        }
    
        public System.Guid DocumentId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<bool> CommentBold { get; set; }
        public System.Guid DocumentCategoryId { get; set; }
        public Nullable<bool> CommentItalic { get; set; }
        public Nullable<bool> CommentUnderline { get; set; }
        public Nullable<int> DaysToComplete { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> DocumentTypeId { get; set; }
        public Nullable<bool> DoesNotRequireManagerSignOff { get; set; }
        public Nullable<bool> TableHeaderBold { get; set; }
        public Nullable<bool> TableHeaderItalic { get; set; }
        public Nullable<bool> TableHeaderUnderline { get; set; }
        public Nullable<bool> InstructionBold { get; set; }
        public Nullable<bool> InstructionItalic { get; set; }
        public Nullable<bool> InstructionUnderline { get; set; }
        public Nullable<System.DateTime> LastUpgradedOn { get; set; }
        public Nullable<bool> PrimaryQuestionBold { get; set; }
        public Nullable<bool> PrimaryQuestionItalic { get; set; }
        public Nullable<bool> PrimaryQuestionUnderline { get; set; }
        public Nullable<bool> QuestionBold { get; set; }
        public Nullable<bool> QuestionItalic { get; set; }
        public Nullable<bool> QuestionUnderline { get; set; }
        public Nullable<bool> SectionBold { get; set; }
        public Nullable<bool> SectionItalic { get; set; }
        public Nullable<bool> SectionUnderline { get; set; }
        public Nullable<bool> SubHeadingBold { get; set; }
        public Nullable<bool> SubHeadingItalic { get; set; }
        public Nullable<bool> SubHeadingUnderline { get; set; }
        public Nullable<bool> SyncQuestionIds { get; set; }
        public Nullable<decimal> Version { get; set; }
        public Nullable<System.Guid> DocumentNameLocalizedStringId { get; set; }
        public Nullable<int> AnswerFontSizeId { get; set; }
        public Nullable<int> CommentFontSizeId { get; set; }
        public Nullable<int> FontStyleId { get; set; }
        public Nullable<int> InstructionBackgroundColorId { get; set; }
        public Nullable<int> InstructionFontColorId { get; set; }
        public Nullable<int> InstructionFontSizeId { get; set; }
        public Nullable<int> PrimaryQuestionBackgroundColorId { get; set; }
        public Nullable<int> PrimaryQuestionFontColorId { get; set; }
        public Nullable<int> PrimaryQuestionFontSizeId { get; set; }
        public Nullable<int> QuestionFontSizeId { get; set; }
        public Nullable<int> QuestionNumberingId { get; set; }
        public Nullable<int> QuestionSubHeadingFontSizeId { get; set; }
        public Nullable<int> SectionFontColorId { get; set; }
        public Nullable<int> SectionFontSizeId { get; set; }
        public Nullable<int> SectionHeadingBackgroundColorId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> TableBorderColorId { get; set; }
        public Nullable<int> TableHeaderBackgroundColorId { get; set; }
        public Nullable<int> TableHeaderFontColorId { get; set; }
        public Nullable<int> TableHeaderFontSizeId { get; set; }
        public Nullable<int> SDEMappingModeId { get; set; }
        public Nullable<int> RuleEvents { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public Nullable<bool> AvailableInMobile { get; set; }
        public Nullable<bool> DisplayPageNumber { get; set; }
        public Nullable<bool> DisableAutoSave { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<bool> ResponsibleUserSelfSignOffAllowed { get; set; }
        public Nullable<bool> AutomaticallyCloseOnCompletion { get; set; }
        public Nullable<bool> MultipleOpenFormsAllowed { get; set; }
        public Nullable<bool> AllowFormStatusCloning { get; set; }
        public Nullable<int> TypeOfDaysId { get; set; }
        public Nullable<bool> CompletionDateAllowedBeforeStartDate { get; set; }
        public Nullable<bool> SignOffDateAllowedBeforeCompletion { get; set; }
        public Nullable<bool> SignOffDateAllowedBeforeStartDate { get; set; }
        public Nullable<bool> ReviewDateAllowedBeforeStartDate { get; set; }
        public Nullable<bool> SignOffDateAllowedBeforeCaseDate { get; set; }
        public Nullable<bool> StartDateallowedBeforeCaseStartDate { get; set; }
        public Nullable<bool> CaseClosureBeforeFormCompletedClosedDate { get; set; }
        public Nullable<System.Guid> ProtectiveMarkingSchemeId { get; set; }
        public Nullable<bool> RecordAssessmentFactor { get; set; }
        public Nullable<bool> EnableReporting { get; set; }
        public string ReportingTableName { get; set; }
        public Nullable<System.DateTime> ReportingLastSyncDateTime { get; set; }
        public Nullable<bool> IsReportingTableInSync { get; set; }
        public Nullable<System.Guid> EdmsDocumentTypeId { get; set; }
        public Nullable<System.Guid> EdmsDocumentSubTypeId { get; set; }
    
        public virtual AttachDocumentType AttachDocumentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseForm> CaseForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentQuestionIdentifier> DocumentQuestionIdentifiers { get; set; }
    }
}
