//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAnswer
    {
        public System.Guid DocumentAnswerId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<System.DateTime> DateAnswer { get; set; }
        public Nullable<System.DateTime> DateAndTimeAnswer { get; set; }
        public Nullable<decimal> DecimalAnswer { get; set; }
        public Nullable<System.Guid> MultichoiceAnswerId { get; set; }
        public Nullable<int> NumericAnswer { get; set; }
        public string ParagraphAnswer { get; set; }
        public string ShortAnswer { get; set; }
        public Nullable<bool> TrueFalseAnswer { get; set; }
        public Nullable<System.Guid> PicklistValueId { get; set; }
        public System.Guid DocumentQuestionIdentifierId { get; set; }
        public System.Guid AssessmentId { get; set; }
        public string AssessmentIdTableName { get; set; }
        public Nullable<System.Guid> LookupObjectId { get; set; }
        public string LookupObjectTypeName { get; set; }
        public string ManagerOverrideReason { get; set; }
        public Nullable<System.Guid> LinkedRecordId { get; set; }
        public string LinkedRecordTypeName { get; set; }
        public Nullable<System.Guid> OriginAnswerId { get; set; }
        public Nullable<bool> UserSaved { get; set; }
        public Nullable<int> GridRowId { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public Nullable<int> QuestionTypeId { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ImageId { get; set; }
        public string LegacyId { get; set; }
        public string LookupObjectTitle { get; set; }
        public string AssessmentIdName { get; set; }
    
        public virtual DocumentQuestionIdentifier DocumentQuestionIdentifier { get; set; }
    }
}
