//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CareDirectorQA_CDEntities : DbContext
    {
        public CareDirectorQA_CDEntities()
            : base("name=CareDirectorQA_CDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssessmentPrintRecord> AssessmentPrintRecords { get; set; }
        public virtual DbSet<TeamRestrictedDataAccess> TeamRestrictedDataAccesses { get; set; }
        public virtual DbSet<UserRestrictedDataAccess> UserRestrictedDataAccesses { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AttachDocumentType> AttachDocumentTypes { get; set; }
        public virtual DbSet<Case> Cases { get; set; }
        public virtual DbSet<CaseAction> CaseActions { get; set; }
        public virtual DbSet<CaseAttachment> CaseAttachments { get; set; }
        public virtual DbSet<CaseForm> CaseForms { get; set; }
        public virtual DbSet<CaseFormOutcome> CaseFormOutcomes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentAnswer> DocumentAnswers { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Letter> Letters { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonAbsenceHospitalStayReason> PersonAbsenceHospitalStayReasons { get; set; }
        public virtual DbSet<PersonAttendedEducationEstablishment> PersonAttendedEducationEstablishments { get; set; }
        public virtual DbSet<PersonCaseNote> PersonCaseNotes { get; set; }
        public virtual DbSet<PersonSignificantEvent> PersonSignificantEvents { get; set; }
        public virtual DbSet<PhoneCall> PhoneCalls { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<DocumentQuestionIdentifier> DocumentQuestionIdentifiers { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<Audit_2018> Audit_2018 { get; set; }
        public virtual DbSet<Audit_2019> Audit_2019 { get; set; }
        public virtual DbSet<Audit_2020> Audit_2020 { get; set; }
        public virtual DbSet<AuditChangeSet> AuditChangeSets { get; set; }
        public virtual DbSet<AuditChangeSet_2018> AuditChangeSet_2018 { get; set; }
        public virtual DbSet<AuditChangeSet_2019> AuditChangeSet_2019 { get; set; }
        public virtual DbSet<AuditChangeSet_2020> AuditChangeSet_2020 { get; set; }      
    }
}
