//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Cases = new HashSet<Case>();
            this.Cases1 = new HashSet<Case>();
            this.CaseActions = new HashSet<CaseAction>();
            this.CaseAttachments = new HashSet<CaseAttachment>();
            this.CaseForms = new HashSet<CaseForm>();
            this.CaseForms1 = new HashSet<CaseForm>();
            this.CaseFormOutcomes = new HashSet<CaseFormOutcome>();
            this.Emails = new HashSet<Email>();
            this.Letters = new HashSet<Letter>();
            this.PersonAttendedEducationEstablishments = new HashSet<PersonAttendedEducationEstablishment>();
            this.PersonCaseNotes = new HashSet<PersonCaseNote>();
            this.PersonSignificantEvents = new HashSet<PersonSignificantEvent>();
            this.PhoneCalls = new HashSet<PhoneCall>();
            this.Tasks = new HashSet<Task>();
        }
    
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> DOBAndAgeTypeId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.Guid> PersonPhotoId { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string FullName { get; set; }
        public string PreferredName { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> MasterId { get; set; }
        public int PersonNumber { get; set; }
        public string NHSNumber { get; set; }
        public Nullable<System.Guid> NoNHSNumberReasonId { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> EthnicityId { get; set; }
        public Nullable<System.Guid> SameAsBirthGenderId { get; set; }
        public Nullable<System.Guid> MaritalStatusId { get; set; }
        public Nullable<System.DateTime> ExpectedDateOfBirth { get; set; }
        public Nullable<bool> Deceased { get; set; }
        public Nullable<System.Guid> CauseOfDeathId { get; set; }
        public string PlaceOfDeath { get; set; }
        public string FullAddress { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string AddressLine1 { get; set; }
        public string Country { get; set; }
        public string AddressLine2 { get; set; }
        public Nullable<System.Guid> AddressPropertyTypeId { get; set; }
        public string AddressLine3 { get; set; }
        public string UPRN { get; set; }
        public string AddressLine4 { get; set; }
        public Nullable<System.Guid> AddressBoroughId { get; set; }
        public string AddressLine5 { get; set; }
        public Nullable<System.Guid> AddressWardId { get; set; }
        public string Postcode { get; set; }
        public Nullable<int> AccommodationStatusId { get; set; }
        public Nullable<int> LivesAloneTypeId { get; set; }
        public string BusinessPhone { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string PrimaryEmail { get; set; }
        public string SecondaryEmail { get; set; }
        public Nullable<bool> RetainInformationConcern { get; set; }
        public Nullable<System.Guid> LanguageId { get; set; }
        public Nullable<System.Guid> ModeOfCommunicationId { get; set; }
        public Nullable<System.Guid> ContactMethodId { get; set; }
        public Nullable<bool> AllowEmail { get; set; }
        public Nullable<bool> AllowMail { get; set; }
        public Nullable<System.Guid> DocumentFormatId { get; set; }
        public Nullable<bool> AllowPhone { get; set; }
        public Nullable<int> PreferredContactTimeId { get; set; }
        public Nullable<int> PreferredContactDayId { get; set; }
        public Nullable<System.Guid> SexualOrientationId { get; set; }
        public Nullable<System.Guid> CountryOfOriginId { get; set; }
        public Nullable<System.Guid> NationalityId { get; set; }
        public Nullable<System.Guid> ImmigrationStatusId { get; set; }
        public Nullable<System.Guid> ReligionId { get; set; }
        public string NHSCardLocation { get; set; }
        public string MaidenName { get; set; }
        public string PlaceOfBirth { get; set; }
        public Nullable<int> AgeGroupId { get; set; }
        public Nullable<System.Guid> PersonTargetGroupId { get; set; }
        public string ExternalNumber { get; set; }
        public string SSDNumber { get; set; }
        public string CourtCaseNumber { get; set; }
        public string NationalInsuranceNumber { get; set; }
        public string NHSNumberPre1995 { get; set; }
        public string BirthCertificateNumber { get; set; }
        public Nullable<bool> IsExternalPerson { get; set; }
        public string FormerUniquePupilNumber { get; set; }
        public string HomeOfficeRegistrationNumber { get; set; }
        public Nullable<System.Guid> UPNUnknownReasonId { get; set; }
        public string CreditorNumber { get; set; }
        public string ReferenceCode { get; set; }
        public string DebtorNumber1 { get; set; }
        public string DebtorNumber2 { get; set; }
        public string DebtorNumber3 { get; set; }
        public string DebtorNumber4 { get; set; }
        public Nullable<bool> SuppressStatementInvoices { get; set; }
        public string Telephone1 { get; set; }
        public string UniquePupilNumber { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<bool> RepresentAlertOrHazard { get; set; }
        public Nullable<bool> AllergiesNotRecorded { get; set; }
        public Nullable<bool> KnownAllergies { get; set; }
        public Nullable<bool> NoKnownAllergies { get; set; }
        public Nullable<bool> InterpreterRequired { get; set; }
        public Nullable<bool> ChildProtectionFlag { get; set; }
        public Nullable<bool> RelatedChildProtectionFlag { get; set; }
        public Nullable<bool> AdultSafeguardingFlag { get; set; }
        public Nullable<bool> RelatedAdultSafeguardingFlag { get; set; }
        public Nullable<bool> RecordedInError { get; set; }
        public Nullable<System.Guid> AccommodationTypeId { get; set; }
        public Nullable<bool> IsLookedAfterChild { get; set; }
        public Nullable<int> ExBritishForcesId { get; set; }
        public Nullable<System.DateTime> AddressStartDate { get; set; }
        public Nullable<System.Guid> CCGBoundaryId { get; set; }
        public Nullable<System.Guid> LowerSuperOutputAreaId { get; set; }
        public Nullable<bool> UpdatePersonAddress { get; set; }
        public Nullable<System.Guid> LinkedAddressId { get; set; }
        public Nullable<bool> AllowSMS { get; set; }
        public Nullable<bool> PDSIsDeferred { get; set; }
        public Nullable<System.DateTime> PDSLastSyncDateTime { get; set; }
        public Nullable<System.Guid> LeavingCareEligibilityId { get; set; }
        public Nullable<bool> PDSNHSNoSuperseded { get; set; }
        public Nullable<int> NHSNumberStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Case> Cases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseAction> CaseActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseAttachment> CaseAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseForm> CaseForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseForm> CaseForms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaseFormOutcome> CaseFormOutcomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letter> Letters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAttendedEducationEstablishment> PersonAttendedEducationEstablishments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCaseNote> PersonCaseNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonSignificantEvent> PersonSignificantEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhoneCall> PhoneCalls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
