//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAttendedEducationEstablishment
    {
        public System.Guid personattendededucationestablishmentid { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<System.Guid> ProviderId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string CurrentYear { get; set; }
        public Nullable<System.Guid> EducationEstablishmentTypeId { get; set; }
        public Nullable<System.Guid> EducationEnrolmentStatusId { get; set; }
        public Nullable<int> AttendedEducationEstablishmentStatusId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.Guid> EducationEndReasonId { get; set; }
        public string ReasonEndedDescription { get; set; }
        public Nullable<System.Guid> HeadTeacherId { get; set; }
        public Nullable<System.Guid> SchoolNurseId { get; set; }
        public Nullable<System.Guid> SENCOId { get; set; }
        public Nullable<System.Guid> SENCOAssistantId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
