//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonSignificantEvent
    {
        public System.Guid PersonSignificantEventId { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventDetails { get; set; }
        public Nullable<System.Guid> SignificantEventCategoryId { get; set; }
        public Nullable<System.Guid> SignificantEventSubCategoryId { get; set; }
        public Nullable<System.Guid> SourceActivityId { get; set; }
        public string SourceActivityIdTableName { get; set; }
        public string SourceActivityIdName { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
