//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneCall
    {
        public System.Guid PhoneCallId { get; set; }
        public byte[] VersionStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public Nullable<System.Guid> ResponsibleUserId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public string Subject { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public Nullable<System.Guid> DataRestrictionId { get; set; }
        public Nullable<System.Guid> RegardingId { get; set; }
        public string RegardingIdTableName { get; set; }
        public string RegardingIdName { get; set; }
        public string Notes { get; set; }
        public Nullable<System.Guid> ActivityCategoryId { get; set; }
        public Nullable<System.Guid> ActivitySubCategoryId { get; set; }
        public Nullable<System.Guid> ActivityOutcomeId { get; set; }
        public Nullable<System.Guid> ActivityReasonId { get; set; }
        public Nullable<System.Guid> ActivityPriorityId { get; set; }
        public Nullable<bool> InformationByThirdParty { get; set; }
        public Nullable<bool> IsSignificantEvent { get; set; }
        public Nullable<System.Guid> SignificantEventCategoryId { get; set; }
        public Nullable<System.Guid> SignificantEventSubCategoryId { get; set; }
        public Nullable<System.DateTime> SignificantEventDate { get; set; }
        public Nullable<System.Guid> CallerId { get; set; }
        public string CallerIdTableName { get; set; }
        public string CallerIdName { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.Guid> RecipientId { get; set; }
        public string RecipientIdTableName { get; set; }
        public string RecipientIdName { get; set; }
        public Nullable<int> DirectionId { get; set; }
        public Nullable<System.DateTime> PhoneCallDate { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
        public Nullable<bool> IsCaseNote { get; set; }
        public Nullable<System.Guid> CaseId { get; set; }
        public Nullable<System.Guid> GroupRecordId { get; set; }
    
        public virtual Case Case { get; set; }
        public virtual Person Person { get; set; }
    }
}
