//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRestrictedDataAccess
    {
        public System.Guid UserRestrictedDataAccessId { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public System.Guid OwnerId { get; set; }
        public System.Guid OwningBusinessUnitId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public Nullable<int> ImportCreateSequence { get; set; }
        public Nullable<int> ImportUpdateSequence { get; set; }
        public string LegacyId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.Guid DataRestrictionReferenceId { get; set; }
    }
}
